### ISSUE TITLE
4.1.0-D6

### ISSUE THREAD

**Issue by malcinator** [GridSpace/grid-apps#329]
Just downloaded and installed (over written) on MacOS 15.3. When I try to open the app i have this error.

<img width="632" alt="Image" src="https://github.com/user-attachments/assets/b81e7a48-4035-4a3d-a7c2-2dbcd59e0fa9" />

The app continues to show its open in the dock but clicking its icon does nothing.

**Comment by stewartoallen** [comment]
fixed by f5406a69d920eac1e02cef764a703e7ece7487e6 and building new binaries now. once you confirm, please close the ticket.

**Comment by malcinator** [comment]
Still getting this error....

<img width="632" alt="Image" src="https://github.com/user-attachments/assets/129cb9d5-9e4d-403b-b5ce-4fe15a20dfb9" />

**Comment by stewartoallen** [comment]
the binary hasn't updated yet. mac build still going. apple notary takes a long time.

<img width="1238" alt="Image" src="https://github.com/user-attachments/assets/61a1bbda-d749-423b-8c35-a0a7458fc45c" />

**Comment by malcinator** [comment]
Alright, I’ll check back later.

Thanks.

Malcolm Summerton
Tel:  <>‭+33 (0) 7 85 97 93 53‬
Mail:  ***@***.***
Telegram: t.me/malcinator

**Comment by stewartoallen** [comment]
though we still may not be out of the woods. the local binary runs fine. when downloaded and tun, it's being treated differently.

**Comment by stewartoallen** [comment]
the current build should be good. I'm not entirely certain what's going on. I rebuilt it several times without making any code changes and several failed while one worked. will have to dig deeper later today when I have time.

**Comment by malcinator** [comment]
That's fixed it. 

Thanks a bunch.
